# Generated by Django 3.2.6 on 2021-09-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_auto_20210904_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='correcta',
            field=models.BooleanField(default=True, null=True, verbose_name='¿Es esta la respuesta correcta?'),
        ),
    ]
